name: Deploy Teamost

on:
  push:
    branches: ['master']

env:
  REGISTRY: crpi-1rw5u2cpo17otwz5.cn-hangzhou.personal.cr.aliyuncs.com
  NAMESPACE: teamost

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nick2806844715
          password: Ghh15377167407.

      - name: Build and push teamost-website
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/teamost-website:latest .
          docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/teamost-website:latest
